spring.application.name=gestor-guias
server.port=8080

# EFS - Almacenamiento temporal
efs.mount.path=/mnt/efs

# AWS S3
aws.s3.bucket-name=guias-despacho-grupo2
aws.region=us-east-1

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update