#  configuración de S3 
spring.application.name=gestor-guias
server.port=8080

# EFS - Almacenamiento temporal
efs.mount.path=/mnt/efs

# bucket. Las credenciales se toman de las variables de entorno.
aws.s3.bucket-name=guias-despacho-grupo2
aws.region=us-east-1

# Forzar actualización - eliminar config
